// --------------------------------------------------------------
// -                        Job  Scripts                        -
// --------------------------------------------------------------

// --------------------------------------------------------------
// ------------------------- Job Quests -------------------------
npc: npc/jobs/novice.txt
npc: npc/jobs/supernovice.txt


npc: npc/jobs/1-1/thief.txt
npc: npc/jobs/1-1/archer.txt
npc: npc/jobs/1-1/mage.txt
npc: npc/jobs/1-1/merchant.txt
npc: npc/jobs/1-1/acolyte.txt
npc: npc/jobs/1-1/swordman.txt

npc: npc/jobs/Jfunc/Jfunc2-1.txt

npc: npc/jobs/2-1/assassin.txt
npc: npc/jobs/2-1/blacksmith.txt
npc: npc/jobs/2-1/hunter.txt
npc: npc/jobs/2-1/knight.txt
npc: npc/jobs/2-1/priest.txt
npc: npc/jobs/2-1/wizard.txt

npc: npc/jobs/2-2/alchemist.txt
npc: npc/jobs/2-2/bard.txt
npc: npc/jobs/2-2/crusader.txt
npc: npc/jobs/2-2/dancer.txt
npc: npc/jobs/2-2/monk.txt
npc: npc/jobs/2-2/rogue.txt
npc: npc/jobs/2-2/sage.txt

npc: npc/quests/skills/acolyte_skills.txt
npc: npc/quests/skills/archer_skills.txt
npc: npc/quests/skills/blacksmith_skill.txt
npc: npc/quests/skills/mage_skills.txt
npc: npc/quests/skills/merchant_skills.txt
npc: npc/quests/skills/novice_skills.txt
npc: npc/quests/skills/swordman_skills.txt
npc: npc/quests/skills/thief_skills.txt